apiVersion: v1
kind: Service
metadata:
  name: jenkins-gcp-instance
  namespace: new-jenkins3
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080  # Port exposed by the service
      targetPort: 8080  # External Jenkins port
  externalIPs:
    - 34.170.235.39  # External Jenkins IP
